export const ACCESS_TOKEN_UPDATE_FAILED = 'ACCESS_TOKEN_UPDATE_FAILED';
export const REFRESH_TOKEN_UPDATE_FAILED = 'REFRESH_TOKEN_UPDATE_FAILED';

export const ACCESS_REFRESH_TOKEN_EXPIRED = 'ACCESS_REFRESH_TOKEN_EXPIRED';
export const ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED';
export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED';
